# Generated by Django 5.2.15 on 2026-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="requirement",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
