# Generated by Django 5.2.15 on 2026-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
